name: DockerMavenPlugin Bug Reproducer

on:
  push:
    branches: [ use-karaf-444-in-docker ]
  pull_request:
    branches: [use-karaf-444-in-docker ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn install
        cd docker
        mvn install
